version: '3.7'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  app:
    container_name: vitta_app
    build: .
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local
